final Map<String, Map<String, dynamic>> groupScenarioDetails = {
  '1. Planning a Party': {
    'description': 'Organize and plan a party for a group of friends.',
    'steps': [
      'Plan the party theme',
      'Set up a party budget',
      'Create a guest list',
      'Decorate the venue',
      'Prepare a playlist and food menu',
    ],
    'image': 'assets/images/greeting_A_friend.png',
    'roles': [
      'Planner:Organizes the party',
      'Friend: Helps with ideas and tasks.',
      'Guest:Attends the party.',
      'Decorator:Handles party decorations.'
    ],
    'dialogues': {
      'Planner': [
        "Let’s pick a theme for the party!",
        "I’ll send out invitations today.",
        "Can you help me set up the decorations?",
        "I’m so excited, it’s almost time!",
        "Thank you all for helping me plan this party!",
      ],
      'Friend': [
        "How about a beach theme?",
        "I’ll help with the snacks!",
        "I’ll bring the music playlist.",
        "Let’s make this the best party ever!",
        "What else do we need to do?",
      ],
      'Guest': [
        "I’m so excited for the party!",
        "This place looks amazing!",
        "Thank you for inviting me!",
        "Can I help with anything?",
        "This is so much fun!",
      ],
      'Decorator': [
        "I’ve got the balloons ready.",
        "The decorations are up! It’s looking great!",
        "Where should I put the streamers?",
        "I’ll make sure everything looks perfect.",
        "The party space is ready!",
      ],
    },
  },
  '2. Shopping at a Grocery Store': {
    'description': 'Go shopping for groceries with a list of items to buy.',
    'steps': [
      'Prepare a shopping list',
      'Select the items from shelves',
      'Pay at the checkout',
      'Pack the groceries',
    ],
    'image': 'assets/images/grocery_store.png',
    'roles': ['Shopper', 'Cashier', 'Store Assistant', 'Friend'],
    'dialogues': {
      'Shopper': [
        "Do you have any tomatoes?",
        "I’ll grab some milk and bread.",
        "Can you help me find the eggs?",
        "How much does this cost?",
        "Thank you for your help!",
      ],
      'Cashier': [
        "Hello! Do you have a shopping list?",
        "Your total is 15.50.",
        "Would you like paper or plastic bags?",
        "Here’s your receipt.",
        "Have a great day!",
      ],
      'Store Assistant': [
        "The tomatoes are in aisle 3.",
        "Let me show you where the eggs are.",
        "We have fresh apples today.",
        "Do you need help with anything else?",
        "The milk is on sale today!",
      ],
      'Friend': [
        "I’ll get the chips if you grab the drinks.",
        "This looks like a great deal!",
        "Let’s check the price of this cereal.",
        "Do we need anything else from this aisle?",
        "This is fun! Let’s shop together again.",
      ],
    },
  },
  '3. Cleaning Up as a Team': {
    'description': 'Work together as a team to clean up a shared space.',
    'steps': [
      'Assign cleaning tasks to each team member',
      'Gather cleaning supplies',
      'Start cleaning the designated areas',
      'Dispose of trash and organize items',
      'Inspect the area to ensure it’s clean',
    ],
    'image': 'assets/images/cleaning_up.png',
    'roles': [
      'Team Leader: Assigns tasks and oversees the process.',
      'Cleaner: Cleans specific areas.',
      'Organizer: Puts items back in place.',
      'Trash Collector: Collects and disposes of trash.',
    ],
    'dialogues': {
      'Team Leader': [
        "Let’s divide the tasks evenly.",
        "Who can clean the living room?",
        "Make sure to check under the furniture.",
        "Great job, everyone! It’s looking much better.",
        "Let’s finish up and take a break!",
      ],
      'Cleaner': [
        "I’ll start with the kitchen counters.",
        "Should I use the vacuum or the broom?",
        "This area is done. What’s next?",
        "I’ll wipe down the windows too.",
        "It’s so satisfying to see it clean!",
      ],
      'Organizer': [
        "I’ll put these books back on the shelf.",
        "Where does this belong?",
        "Let’s arrange the chairs neatly.",
        "I’ll organize the pantry.",
        "Everything looks so tidy now!",
      ],
      'Trash Collector': [
        "I’ll take out the trash bags.",
        "Do we have a recycling bin?",
        "I’ll check the bins in every room.",
        "The trash is all cleared out.",
        "Let’s make sure nothing is left behind.",
      ],
    },
  },
  '4. Storytelling Circle': {
    'description': 'Sit in a circle and take turns telling stories.',
    'steps': [
      'Gather in a circle',
      'Choose a theme or topic for the stories',
      'Take turns telling stories',
      'Listen and react to each story',
      'Applaud and thank each storyteller',
    ],
    'image': 'assets/images/storytelling_circle.png',
    'roles': [
      'Storyteller: Shares a story with the group.',
      'Listener: Listens and reacts to the stories.',
      'Moderator: Keeps the circle organized.',
    ],
    'dialogues': {
      'Storyteller': [
        "Once upon a time, there was a brave knight...",
        "This story is about a magical forest.",
        "Let me tell you about my favorite adventure.",
        "And then, the dragon appeared!",
        "The end. I hope you enjoyed it!",
      ],
      'Listener': [
        "Wow, that was amazing!",
        "What happened next?",
        "I love this part of the story!",
        "That’s so funny!",
        "Thank you for sharing!",
      ],
      'Moderator': [
        "Let’s start with the first storyteller.",
        "Who would like to go next?",
        "Remember to keep the stories short.",
        "Let’s give a round of applause!",
        "Thank you all for participating!",
      ],
    },
  },
  '5. Group Project': {
    'description': 'Collaborate with a group to complete a project.',
    'steps': [
      'Assign roles and tasks to each member',
      'Research and gather information',
      'Work on individual tasks',
      'Combine all parts into the final project',
      'Present the project to the class',
    ],
    'image': 'assets/images/group_project.png',
    'roles': [
      'Leader: Oversees the project and assigns tasks.',
      'Researcher: Gathers information and data.',
      'Designer: Creates visuals and layouts.',
      'Presenter: Presents the final project.',
    ],
    'dialogues': {
      'Leader': [
        "Let’s divide the work evenly.",
        "Who can handle the research part?",
        "We need to finish this by Friday.",
        "Great job, everyone! It’s coming together.",
        "Let’s rehearse the presentation.",
      ],
      'Researcher': [
        "I found some great sources for our project.",
        "Should I include this data?",
        "I’ll summarize the key points.",
        "This information is really helpful.",
        "Let me know if you need more details.",
      ],
      'Designer': [
        "I’ll create the slides for the presentation.",
        "What colors should we use?",
        "I’ll add some visuals to make it engaging.",
        "The layout is almost done.",
        "Let’s make sure everything looks neat.",
      ],
      'Presenter': [
        "I’ll start with the introduction.",
        "Let’s practice the flow of the presentation.",
        "I’ll make sure to explain everything clearly.",
        "We’re ready to present!",
        "Thank you all for your hard work!",
      ],
    },
  },
  '6. Playing at the Park': {
    'description': 'Spend time playing games and having fun at the park.',
    'steps': [
      'Choose a game or activity to play',
      'Set up the game or gather equipment',
      'Play the game together',
      'Take breaks and hydrate',
      'Clean up before leaving',
    ],
    'image': 'assets/images/playing_at_park.png',
    'roles': [
      'Game Leader: Organizes the games.',
      'Player: Participates in the games.',
      'Equipment Manager: Handles the equipment.',
      'Cheerleader: Encourages everyone.',
    ],
    'dialogues': {
      'Game Leader': [
        "Let’s play tag first!",
        "Who wants to be the referee?",
        "Let’s switch to a new game.",
        "Great job, everyone!",
        "Let’s clean up before we leave.",
      ],
      'Player': [
        "I’ll join the soccer game!",
        "This is so much fun!",
        "Can we play hide and seek next?",
        "I’m getting tired. Let’s take a break.",
        "Thanks for playing with me!",
      ],
      'Equipment Manager': [
        "I’ll bring the ball.",
        "Let’s set up the frisbee.",
        "Don’t forget the water bottles.",
        "I’ll pack everything up.",
        "We have all the equipment ready.",
      ],
      'Cheerleader': [
        "You’re doing great!",
        "Keep going, you’ve got this!",
        "Let’s cheer for the team!",
        "This is so much fun!",
        "You’re all amazing!",
      ],
    },
  },
  '7. Going to a Restaurant': {
    'description':
        'Visit a restaurant and enjoy a meal with friends or family.',
    'steps': [
      'Choose a restaurant',
      'Decide on the menu items to order',
      'Place the order with the waiter',
      'Enjoy the meal together',
      'Pay the bill and leave a tip',
    ],
    'image': 'assets/images/restaurant.png',
    'roles': [
      'Customer: Orders food and enjoys the meal.',
      'Waiter: Takes orders and serves food.',
      'Friend: Shares the meal and conversation.',
      'Cashier: Handles the payment.',
    ],
    'dialogues': {
      'Customer': [
        "I’ll have the pasta, please.",
        "Can we get some water too?",
        "This dish is delicious!",
        "Can I have the dessert menu?",
        "Thank you for the great service!",
      ],
      'Waiter': [
        "Welcome! Here’s the menu.",
        "Are you ready to order?",
        "Your food will be out shortly.",
        "How is everything tasting?",
        "Here’s your bill. Thank you!",
      ],
      'Friend': [
        "Let’s share the appetizer.",
        "This place has such a nice vibe.",
        "I’ll try the steak.",
        "Let’s take a picture of the food!",
        "This was such a great meal!",
      ],
      'Cashier': [
        "Your total is 45.50dollors.",
        "Would you like to pay by card?",
        "Here’s your receipt.",
        "Thank you for dining with us!",
        "Have a wonderful day!",
      ],
    },
  },
  '8. Visiting a Doctor': {
    'description': 'Visit a doctor for a check-up or consultation.',
    'steps': [
      'Schedule an appointment',
      'Arrive at the clinic and check in',
      'Describe symptoms or concerns to the doctor',
      'Follow the doctor’s advice or treatment plan',
      'Pay the bill and schedule a follow-up if needed',
    ],
    'image': 'assets/images/visiting_doctor.png',
    'roles': [
      'Patient: Seeks medical advice or treatment.',
      'Doctor: Diagnoses and provides treatment.',
      'Receptionist: Manages appointments and check-ins.',
      'Nurse: Assists the doctor and patient.',
    ],
    'dialogues': {
      'Patient': [
        "I’ve been feeling unwell lately.",
        "I have a headache and a fever.",
        "Should I take any medication?",
        "Thank you for your help, Doctor.",
        "I’ll follow your advice.",
      ],
      'Doctor': [
        "What symptoms are you experiencing?",
        "Let me check your temperature.",
        "You need to take this medicine twice a day.",
        "Make sure to rest and drink plenty of water.",
        "Come back if the symptoms persist.",
      ],
      'Receptionist': [
        "Do you have an appointment?",
        "Please fill out this form.",
        "The doctor will see you shortly.",
        "Your insurance covers this visit.",
        "Here’s your receipt and next appointment.",
      ],
      'Nurse': [
        "Let me take your blood pressure.",
        "The doctor will be with you in a moment.",
        "Please wait in the examination room.",
        "Here’s the prescription from the doctor.",
        "Take care and get well soon!",
      ],
    },
  },
  '9. Attending a Birthday Party': {
    'description': 'Celebrate a friend or family member’s birthday at a party.',
    'steps': [
      'Arrive at the party venue',
      'Greet the host and other guests',
      'Participate in party activities and games',
      'Sing "Happy Birthday" and enjoy the cake',
      'Thank the host and say goodbye',
    ],
    'image': 'assets/images/birthday_party.png',
    'roles': [
      'Birthday Person: Celebrates their special day.',
      'Guest: Attends the party and participates.',
      'Host: Organizes the party and welcomes guests.',
      'Entertainer: Leads games and activities.',
    ],
    'dialogues': {
      'Birthday Person': [
        "Thank you all for coming!",
        "I’m so happy to celebrate with you.",
        "Let’s cut the cake together!",
        "This is the best birthday ever!",
        "I’ll open the gifts now.",
      ],
      'Guest': [
        "Happy Birthday! Here’s your gift.",
        "This party is so much fun!",
        "Let’s play the next game.",
        "The cake looks delicious!",
        "Thank you for inviting me!",
      ],
      'Host': [
        "Welcome to the party!",
        "Let’s start with some games.",
        "Time to sing 'Happy Birthday'!",
        "Enjoy the food and drinks!",
        "Thank you all for coming!",
      ],
      'Entertainer': [
        "Let’s play musical chairs!",
        "Who’s ready for a dance-off?",
        "Here’s the next activity!",
        "You’re all doing great!",
        "Let’s keep the fun going!",
      ],
    },
  },
  '10. Classroom Experience': {
    'description': 'Participate in a classroom lesson and activities.',
    'steps': [
      'Enter the classroom and take a seat',
      'Listen to the teacher’s instructions',
      'Participate in the lesson or activity',
      'Ask questions or share ideas',
      'Complete the assigned work',
    ],
    'image': 'assets/images/classroom_experience.png',
    'roles': [
      'Teacher: Leads the lesson and guides students.',
      'Student: Participates in the lesson and activities.',
      'Class Monitor: Helps the teacher and classmates.',
      'Librarian: Manages classroom resources.',
    ],
    'dialogues': {
      'Teacher': [
        "Good morning, class! Let’s begin.",
        "Today, we’ll learn about math.",
        "Does anyone have questions?",
        "Great job, everyone!",
        "Don’t forget to do your homework.",
      ],
      'Student': [
        "I have a question about the lesson.",
        "Can you explain that again?",
        "I’ll work on this problem.",
        "This activity is really fun!",
        "Thank you, Teacher!",
      ],
      'Class Monitor': [
        "I’ll collect the homework.",
        "Let’s keep the classroom tidy.",
        "Can I help with the activity?",
        "Everyone, please raise your hands.",
        "The teacher needs our attention.",
      ],
      'Librarian': [
        "Here are the books for today’s lesson.",
        "Let’s return the books after class.",
        "Do you need any extra materials?",
        "The library is open for borrowing.",
        "Take care of the books, please.",
      ],
    },
  },
};
